version: "3.7"
networks:
  default:
    external:
      name: bot
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python api.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
